# Generated by Django 5.0.2 on 2024-02-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceDateBase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('name', models.TextField()),
                ('ticker', models.TextField()),
                ('start_price', models.IntegerField()),
                ('high_price', models.IntegerField()),
                ('low_price', models.IntegerField()),
                ('end_price', models.IntegerField()),
                ('fluctuation_rate', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('volume_amount', models.IntegerField()),
                ('per', models.IntegerField()),
                ('bps', models.IntegerField()),
                ('pbr', models.IntegerField()),
                ('eps', models.IntegerField()),
                ('div', models.IntegerField()),
                ('dps', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
