# Generated by Django 5.0.2 on 2024-02-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='bps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='div',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='dps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='eps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='pbr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='per',
            field=models.IntegerField(null=True),
        ),
    ]
