# Generated by Django 5.0.2 on 2024-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0002_alter_stockpricedatebase_bps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='bps',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='div',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='dps',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='eps',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='pbr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='per',
            field=models.TextField(),
        ),
    ]
