# Generated by Django 5.0.2 on 2024-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0003_alter_stockpricedatebase_bps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceDB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('name', models.TextField()),
                ('ticker', models.TextField()),
                ('start_price', models.IntegerField()),
                ('high_price', models.IntegerField()),
                ('low_price', models.IntegerField()),
                ('end_price', models.IntegerField()),
                ('fluctuation_rate', models.FloatField()),
                ('volume', models.IntegerField()),
                ('volume_amount', models.IntegerField()),
                ('per', models.TextField()),
                ('bps', models.TextField()),
                ('pbr', models.TextField()),
                ('eps', models.TextField()),
                ('div', models.TextField()),
                ('dps', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='fluctuation_rate',
            field=models.FloatField(),
        ),
    ]
