# Generated by Django 5.0.2 on 2024-02-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0004_stockpricedb_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPriceDB',
        ),
    ]
