# Generated by Django 5.0.2 on 2024-02-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0005_delete_stockpricedb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpricedatebase',
            name='created_at',
        ),
    ]
