# Generated by Django 5.0.2 on 2024-02-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0006_remove_stockpricedatebase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricedatebase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
