# Generated by Django 5.0.2 on 2024-02-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0007_alter_stockpricedatebase_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNameAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ticker', models.TextField()),
            ],
        ),
    ]
