# Generated by Django 5.0.2 on 2024-02-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0008_stocknameall'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPricePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('analysis_period', models.IntegerField()),
                ('start_day', models.TextField()),
                ('end_day', models.TextField()),
                ('price_list', models.TextField()),
                ('fluctuation_list', models.TextField()),
                ('MA224_list', models.TextField()),
                ('MA224_rate_list', models.TextField()),
                ('MA224_mean_list', models.TextField()),
                ('MA224_std_list', models.TextField()),
            ],
        ),
    ]
