# Generated by Django 5.0.2 on 2024-03-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0010_delete_stocknameall_delete_stockpricepattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPricePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('analysis_period', models.IntegerField()),
                ('start_day', models.TextField()),
                ('end_day', models.TextField()),
                ('price_list', models.TextField()),
                ('fluctuation_list', models.TextField()),
                ('MA224_list', models.TextField()),
                ('MA224_ratio_list', models.TextField()),
                ('rate_MA224_mean_list', models.TextField()),
                ('rate_MA224_std_list', models.TextField()),
            ],
        ),
    ]
