# Generated by Django 5.0.2 on 2024-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0011_stockpricepattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricepattern',
            name='yield_20days',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='stockpricepattern',
            name='yield_5days',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='stockpricepattern',
            name='yield_60days',
            field=models.TextField(default=None),
        ),
    ]
