# Generated by Django 5.0.2 on 2024-03-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpattern', '0015_stockpricepattern_rate_volume_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
            ],
        ),
    ]
